### PR TITLE
Enable Blur 

### PR DESCRIPTION
**Pull request by leskal**
- Uses blur library addition in vendor commit,
  and frameworks native commit "surfaceflinger: Cleanups for blur"
  http://review.cyanogenmod.org/#/c/154666/ by Steve Kondik

### CODE REVIEW

**Comment by JonnyVR1** [comment]
Apparently causes frequent reboots? http://review.cyanogenmod.org/#/c/155031/

**Comment by leskal** [comment]
The change commit you show about frequent reboots has been abandoned, also i have xperia sp and it hasn't reboots with blur enable

**Comment by JonnyVR1** [comment]
Merged

**Comment by JonnyVR1** [comment]
Reverted merge, we don't have the libuiblur.so vendor blob

**Pull request closed without merging**
